### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by lazystone** [personnummer/java#27] opened 2020-09-25 14:54 UTC
First of all - stor tack for the library!

Would it be possible for you to publish it to Maven Central to avoid hassle of dealing with GitHub packages?

**Comment by lazystone** [comment] 2020-09-25 15:07
By the "hassle" I mean [this](https://github.community/t/download-from-github-package-registry-without-authentication/14407/4).

Even though it's possible to download artifacts without authentication, it's not possible to configure maven/gradle without authentication token. And forcing all developers do that just for GitHub packages seems a bit unreasonable :disappointed:

**Comment by Johannestegner** [comment] 2020-09-25 17:29
Hi there @lazystone!

I have considered doing this, but I haven't worked a lot with java for the last... 10 years or so, so was not sure if MC was "the thing" to go for now 'a days! But yes, it would absolutely be possible to do it!
Sorry for not doing it earlier, hehe, but I will try to get it done asap :)

Also: happy to provide and thanks for using it! :)

**Comment by Johannestegner** [comment] 2020-10-02 08:41
Hi @lazystone ! I was just wondering a bit... Is this the "Maven Central" that you are refering to https://oss.sonatype.org/ ? Just so that I don't sign up and fix keys and all that fun stuff and it ends up being the wrong repository :D

**Comment by lazystone** [comment] 2020-10-02 08:43
Heh..I guess it's this one(never published to Maven Central myself).

I found an article with instructions though: https://dzone.com/articles/publish-your-artifacts-to-maven-central

**Comment by lazystone** [comment] 2020-10-02 08:44
Also https://maven.apache.org/repository/guide-central-repository-upload.html

**Comment by Johannestegner** [comment] 2020-10-02 08:46
Super, thank you. 
Aye, I found the same DZone Article. It seems like publishing to maven is a lot more work than a lot of other centralized package repositories, but looking at Java, it doesn't suprice me! ;D

I will try to make it work today, worst case it will be published in the beginning of next week or so :)

**Comment by Johannestegner** [comment] 2020-10-02 08:59
https://issues.sonatype.org/browse/OSSRH-61073

I've created an issue on their Jira board and we will see what happens! :)

**Comment by Johannestegner** [comment] 2020-10-05 07:05
I have been trying to get this to run during the weekend, it's a whole lot more of a hassle than I though.
I have created an account on OSSRH so that I can publish artifacts, the issue now is that there are aprox 0 good writeups on how to publish from github to the central repository.  
I have found a bunch of different resources for uploading artifacts, but some are very old (the sonatype seems to be from 2013, the github one is missing the quite important step of how to sign the archives etc etc...)

I will keep on trying to get it to work, and if anyone have any idea how to do it or have an example deploy script with a working gradle.build file, let me know!

**Comment by lazystone** [comment] 2020-10-05 07:25
Hi @Johannestegner,

I guess that first of all you need to add username, password for maven central as environment variables. Something like `MAVEN_CENTRAL_USERNAME` and `MAVEN_CENTRAL_PASSWORD`.

Then you can try to add new repo to your gradle file:
```groovy
publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/personnummer/java")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
            }
        }
    }
    repositories {
        maven {
            credentials {
                username = project.findProperty("maven.central.user") ?: System.getenv("MAVEN_CENTRAL_USERNAME")
                password = project.findProperty("maven.central.password") ?: System.getenv("MAVEN_CENTRAL_PASSWORD")
            }
            if (project.version.endsWith('-SNAPSHOT')) {
                url "https://oss.sonatype.org/content/repositories/snapshots"
            } else {
                url "https://oss.sonatype.org/service/local/staging/deploy/maven2"
            }
        }
    }
    publications {
        gpr(MavenPublication) {
            version = System.getenv("RELEASE_VERSION")
            groupId = 'dev.personnummer'

            from components.java
        }
    }
}
```

Snippet above was shamelessly stolen from [this answer](https://stackoverflow.com/questions/16750222/publish-snapshot-vs-publish-release-in-gradle-with-continuous-integration)

**Comment by Johannestegner** [comment] 2020-10-05 07:51
@lazystone Thank you!

Yes, I got that far (although it have to be written slightly different now' a days), but the signing part is pretty much the part that I fail to implement in a decent way... hehe...

The central requires the following things in the archive uploaded: jar, javadocs, source.
The archive (or maybe only jar?) have to be signed with GPG/PGP, I have no issues setting up a key and all that, but the process is very unclear.

It feels like there should be some typ of github action to automate this, but I can't find any at all, which is quite odd in my opinion.

**Comment by lazystone** [comment] 2020-10-05 07:56
For signing you should probably leverage gradle as well rather than GitHub actions(rule of thumb - process should be independent from GitHub as much as possible :wink:  ).

There is a signing plugin: https://docs.gradle.org/current/userguide/signing_plugin.html

Seems like you can provide signing key and password as an environment variables as well.

**Comment by Johannestegner** [comment] 2020-10-05 07:59
Aye, that was my thought too, tried to get that working earlier without luck. But I'll try some more and see if I can make it work!

Thanks for the resources :)

**Comment by Johannestegner** [comment] 2020-10-08 19:34
Just awaiting the staged release to be published and this issue will close.
The package is published as `dev.personnummer` :)

**Comment by Johannestegner** [comment] 2020-10-09 09:29
> Central OSSRH added a comment - 18 minutes ago
> Central sync is activated for dev.personnummer. After you successfully release, your component will be published to Central,  typically within 10 minutes, though updates to search.maven.org can take up to two hours.

So it should be live and working as intended now. Packages are signed, source and docs are included in the release and the CI script is set up to be able to build and deploy with signing and all!
To publish to maven-central was more annoying than I thought it was, but at the least it's fixed now, haha.

Let me know if there are any issues, closing this request now!

**Closed by Johannestegner** 2020-10-09 09:29 UTC
Labels: enhancement, help wanted
