### ISSUE TITLE
[FEATURE] - Implementing Java-specific methods?

### ISSUE THREAD

**Issue by ullenius** [personnummer/java#23] opened 2020-06-25 21:49 UTC
**A Modest Proposal**

Implementing some Java specific methods might be beneficial, such as:

1. Overriding `equals()`
1. Overriding `hashCode()`

1. Overriding `toString()` - perhaps returning the `format()`method?
1. Implementing `Comparable<Personnummer>` for sorting.

For 1 and 2 behaviour needs to specified.

**Comment by Johannestegner** [comment] 2020-06-25 22:43
I do absolutely think this is a good idea!
I will talk to the team tomorrow and see what they think about it!

I personally feel that `Personnummer.parse("19851003-3999");` and `Personnummer.parse("8510033999");` are equal in a compare/equal check. Do you agree?

**Comment by ullenius** [comment] 2020-06-26 06:40
> I personally feel that `Personnummer.parse("19851003-3999");` and `Personnummer.parse("8510033999");` are equal in a compare/equal check. Do you agree?

IMHO this is a matter of opinion. It is up to the team to decide.

Personally, I think it would be great if equals could differentiate between:

201701012393 - (170101-2393)
191701012393 - (170101+2393)

The former is a 3 year old boy and the latter a 103 year old man. 

Perhaps multiple equals methods? For example Java's String class has two equals methods: `equalsIgnoreCase()` and `equals()`

**Comment by Johannestegner** [comment] 2020-06-26 09:32
> Personally, I think it would be great if equals could differentiate between:
> 
> 201701012393 - (170101-2393)
> 191701012393 - (170101+2393)
> 
> The former is a 3 year old boy and the latter a 103 year old man.

Yes, that would be the intended behavior. The data in the Personnummer object contains all the information required to diff between the two, so should not be an issue :)

**Comment by bombsimon** [comment] 2020-06-26 09:42
What would `20170101+2393` result in today? The century is explicitly set 2000 but it also indicates that a person is over 100 years old. Maybe that format is invalid? 🤔

**Comment by Johannestegner** [comment] 2020-06-26 09:58
> 
> 
> What would `20170101+2393` result in today? The century is explicitly set 2000 but it also indicates that a person is over 100 years old. Maybe that format is invalid? 🤔

Yes, it is basically an invalid format, but the parse function will allow it and prioritize on the century and ignore the `+`. The `-/+` is used in case there is no century and if there is neither, it will use the closest year.

**Comment by Johannestegner** [comment] 2020-06-26 10:01
I do think that the easiest way to compare two numbers is by using the `format` method basically.
It will result in a full personnummer string containing all the data required.

So, basically:

```
public function equals(Personnummer personnummer) {
  return format().equals(personnummer.format());
}
```

should work.

**Comment by ullenius** [comment] 2020-06-26 10:52
> So, basically:
> 
> ```
> public function equals(Personnummer personnummer) {
>   return format().equals(personnummer.format());
> }
> ```

I made a pull request where I implemented this and the `hashCode()` method.

However I used the long-format, i.e. `format(true)`

Please see #24

**Comment by Johannestegner** [comment] 2020-06-26 21:01
I think that when it comes to comparable, the easiest way would be to just convert it into a timestamp (maybe we should even store that in a var?) and sort on that.

**Comment by ullenius** [comment] 2020-06-26 21:23
> I think that when it comes to comparable, the easiest way would be to just convert it into a timestamp (maybe we should even store that in a var?) and sort on that.

Won't it just work out of the box with String's `compareTo()` method? "Compares two strings lexicographically" ([Javadocs](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#compareTo-java.lang.String-))

```
@Override
public int compareTo(Personnummer other) {

	return format(true).compareTo(other.format(true));
}
```

**Comment by Johannestegner** [comment] 2020-06-26 21:29
Yes, you are right, I even thing a none-long formated version would work (seeing ascii wise + is before -) but I think that long version is the best way to go :)

**Comment by Johannestegner** [comment] 2020-06-27 08:28
Seeing all the changes are implemented, I'll close this issue! Thanks for the contribution :)

**Closed by Johannestegner** 2020-06-27 08:28 UTC
Labels: enhancement
